runtime: python39  # or python38 or python310, depending on your needs

entrypoint: gunicorn -b :$PORT main:app -t 1800 --keep-alive 1800  # Assuming your Flask app instance is named 'app' in 'main.py'

instance_class: F2  # This specifies the machine type. Optional and can be adjusted based on your needs.

automatic_scaling:
  min_instances: 1  # Keep at least one instance running
  max_instances: 2  # Adjust based on expected traffic
  target_cpu_utilization: 0.65  # Adjust as needed
  target_throughput_utilization: 0.75  # Adjust as needed

inbound_services:
- warmup

env_variables:
  MONGO_URI: mongodb+srv://andrecalder98:LFgw87KNYZ2OjZOK@qgo.xywmfco.mongodb.net/?retryWrites=true&w=majority&appName=qGo
  ACCESS_TOKEN_SECRET: NAdLExsZag2dcIfzUYYsUE7r8b8qvpbyMSa7vX0LPTE
  REFRESH_TOKEN_SECRET: oCpn8bWykq3NIwIL3osX6uZIFAKnGjRtntsuHPgs_PE
  PORT: 8080

handlers:

- url: /.*
  script: auto